


# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.
# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2

name: insurance_demo
channels:
  - defaults
  - conda-forge
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.8.5
  - pip>=19.1.1
  - numpy>=1.13.3
  - pandas>=0.25.1
  - pytest>=3.6.4
  - pip:
      - azureml-sdk
      - azureml-defaults
      #- scikit-learn>=0.19.0,<=0.20.3
      - scikit-learn>=0.22.1
      - requests==2.22.0
      - requests-oauthlib==1.2.0
      - regex==2020.2.20
      - seaborn
      - joblib